# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alarm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(768, 457)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdNumber.setGeometry(QtCore.QRect(20, 60, 271, 81))
        self.lcdNumber.setStyleSheet("font: bold 11pt \"Tlwg Mono\";")
        self.lcdNumber.setObjectName("lcdNumber")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(-90, 250, 1051, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(630, 10, 131, 231))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton.setStyleSheet("font: 18pt \"Tlwg Mono\";")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_2.setStyleSheet("font: 18pt \"Tlwg Mono\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_3.setStyleSheet("font: 18pt \"Tlwg Mono\";")
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_4.setStyleSheet("font: 18pt \"Tlwg Mono\";")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 270, 341, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setStyleSheet("font: bold 11pt \"Tlwg Mono\";")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.horizontalSlider = QtWidgets.QSlider(self.layoutWidget1)
        self.horizontalSlider.setStyleSheet("QSlider::groove:horizontal {\n"
"    border: 1px solid #999999;\n"
"    height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
"    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
"    margin: 2px 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
"    border: 1px solid #5c5c5c;\n"
"    width: 18px;\n"
"    margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
"    border-radius: 3px;\n"
"}")
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.verticalLayout_2.addWidget(self.horizontalSlider)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(380, 10, 241, 231))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.toolButton_2 = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_2.setStyleSheet("QToolButton {\n"
"font: 18pt \"Tlwg Mono\"; \n"
"border-radius: 10px; \n"
"border-color: black;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"background-color: rgb(211, 215, 207); \n"
"}\n"
"QToolButton::pressed {\n"
"  font: 18pt \"Tlwg Mono\"; \n"
"  border-radius: 10px; \n"
"  border-color: black;\n"
"  border-width: 2px;\n"
"  border-style: inset;\n"
"  background-color: rgb(238, 238, 236);\n"
"}")
        self.toolButton_2.setAutoRepeatDelay(305)
        self.toolButton_2.setAutoRaise(False)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout.addWidget(self.toolButton_2, 0, 0, 1, 1)
        self.toolButton_5 = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_5.setStyleSheet("QToolButton {\n"
"font: 18pt \"Tlwg Mono\"; \n"
"border-radius: 10px; \n"
"border-color: black;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"background-color: rgb(211, 215, 207); \n"
"}\n"
"QToolButton::pressed {\n"
"  font: 18pt \"Tlwg Mono\"; \n"
"  border-radius: 10px; \n"
"  border-color: black;\n"
"  border-width: 2px;\n"
"  border-style: inset;\n"
"  background-color: rgb(238, 238, 236);\n"
"}")
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout.addWidget(self.toolButton_5, 1, 0, 1, 1)
        self.toolButton_9 = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_9.setStyleSheet("QToolButton {\n"
"font: 18pt \"Tlwg Mono\"; \n"
"border-radius: 10px; \n"
"border-color: black;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"background-color: rgb(211, 215, 207); \n"
"}\n"
"QToolButton::pressed {\n"
"  font: 18pt \"Tlwg Mono\"; \n"
"  border-radius: 10px; \n"
"  border-color: black;\n"
"  border-width: 2px;\n"
"  border-style: inset;\n"
"  background-color: rgb(238, 238, 236);\n"
"}")
        self.toolButton_9.setObjectName("toolButton_9")
        self.gridLayout.addWidget(self.toolButton_9, 2, 2, 1, 1)
        self.toolButton_13 = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_13.setStyleSheet("QToolButton {\n"
"font: 18pt \"Tlwg Mono\"; \n"
"border-radius: 10px; \n"
"border-color: black;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"background-color: rgb(211, 215, 207); \n"
"}\n"
"QToolButton::pressed {\n"
"  font: 18pt \"Tlwg Mono\"; \n"
"  border-radius: 10px; \n"
"  border-color: black;\n"
"  border-width: 2px;\n"
"  border-style: inset;\n"
"  background-color: rgb(238, 238, 236);\n"
"}")
        self.toolButton_13.setObjectName("toolButton_13")
        self.gridLayout.addWidget(self.toolButton_13, 3, 1, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_3.setStyleSheet("QToolButton {\n"
"font: 18pt \"Tlwg Mono\"; \n"
"border-radius: 10px; \n"
"border-color: black;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"background-color: rgb(211, 215, 207); \n"
"}\n"
"QToolButton::pressed {\n"
"  font: 18pt \"Tlwg Mono\"; \n"
"  border-radius: 10px; \n"
"  border-color: black;\n"
"  border-width: 2px;\n"
"  border-style: inset;\n"
"  background-color: rgb(238, 238, 236);\n"
"}")
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout.addWidget(self.toolButton_3, 0, 1, 1, 1)
        self.toolButton_4 = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_4.setStyleSheet("QToolButton {\n"
"font: 18pt \"Tlwg Mono\"; \n"
"border-radius: 10px; \n"
"border-color: black;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"background-color: rgb(211, 215, 207); \n"
"}\n"
"QToolButton::pressed {\n"
"  font: 18pt \"Tlwg Mono\"; \n"
"  border-radius: 10px; \n"
"  border-color: black;\n"
"  border-width: 2px;\n"
"  border-style: inset;\n"
"  background-color: rgb(238, 238, 236);\n"
"}")
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout.addWidget(self.toolButton_4, 0, 2, 1, 1)
        self.toolButton_10 = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_10.setStyleSheet("QToolButton {\n"
"font: 18pt \"Tlwg Mono\"; \n"
"border-radius: 10px; \n"
"border-color: black;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"background-color: rgb(211, 215, 207); \n"
"}\n"
"QToolButton::pressed {\n"
"  font: 18pt \"Tlwg Mono\"; \n"
"  border-radius: 10px; \n"
"  border-color: black;\n"
"  border-width: 2px;\n"
"  border-style: inset;\n"
"  background-color: rgb(238, 238, 236);\n"
"}")
        self.toolButton_10.setObjectName("toolButton_10")
        self.gridLayout.addWidget(self.toolButton_10, 2, 1, 1, 1)
        self.toolButton_7 = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_7.setStyleSheet("QToolButton {\n"
"font: 18pt \"Tlwg Mono\"; \n"
"border-radius: 10px; \n"
"border-color: black;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"background-color: rgb(211, 215, 207); \n"
"}\n"
"QToolButton::pressed {\n"
"  font: 18pt \"Tlwg Mono\"; \n"
"  border-radius: 10px; \n"
"  border-color: black;\n"
"  border-width: 2px;\n"
"  border-style: inset;\n"
"  background-color: rgb(238, 238, 236);\n"
"}")
        self.toolButton_7.setObjectName("toolButton_7")
        self.gridLayout.addWidget(self.toolButton_7, 1, 1, 1, 1)
        self.toolButton_12 = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_12.setStyleSheet("QToolButton {\n"
"font: 18pt \"Tlwg Mono\"; \n"
"border-radius: 10px; \n"
"border-color: black;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"background-color: rgb(211, 215, 207); \n"
"}\n"
"QToolButton::pressed {\n"
"  font: 18pt \"Tlwg Mono\"; \n"
"  border-radius: 10px; \n"
"  border-color: black;\n"
"  border-width: 2px;\n"
"  border-style: inset;\n"
"  background-color: rgb(238, 238, 236);\n"
"}")
        self.toolButton_12.setObjectName("toolButton_12")
        self.gridLayout.addWidget(self.toolButton_12, 3, 2, 1, 1)
        self.toolButton_11 = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_11.setStyleSheet("QToolButton {\n"
"font: 18pt \"Tlwg Mono\"; \n"
"border-radius: 10px; \n"
"border-color: black;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"background-color: rgb(211, 215, 207); \n"
"}\n"
"QToolButton::pressed {\n"
"  font: 18pt \"Tlwg Mono\"; \n"
"  border-radius: 10px; \n"
"  border-color: black;\n"
"  border-width: 2px;\n"
"  border-style: inset;\n"
"  background-color: rgb(238, 238, 236);\n"
"}")
        self.toolButton_11.setObjectName("toolButton_11")
        self.gridLayout.addWidget(self.toolButton_11, 3, 0, 1, 1)
        self.toolButton_6 = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_6.setStyleSheet("QToolButton {\n"
"font: 18pt \"Tlwg Mono\"; \n"
"border-radius: 10px; \n"
"border-color: black;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"background-color: rgb(211, 215, 207); \n"
"}\n"
"QToolButton::pressed {\n"
"  font: 18pt \"Tlwg Mono\"; \n"
"  border-radius: 10px; \n"
"  border-color: black;\n"
"  border-width: 2px;\n"
"  border-style: inset;\n"
"  background-color: rgb(238, 238, 236);\n"
"}")
        self.toolButton_6.setObjectName("toolButton_6")
        self.gridLayout.addWidget(self.toolButton_6, 1, 2, 1, 1)
        self.toolButton_8 = QtWidgets.QToolButton(self.layoutWidget2)
        self.toolButton_8.setStyleSheet("QToolButton {\n"
"font: 18pt \"Tlwg Mono\"; \n"
"border-radius: 10px; \n"
"border-color: black;\n"
"border-width: 2px;\n"
"border-style: outset;\n"
"background-color: rgb(211, 215, 207); \n"
"}\n"
"QToolButton::pressed {\n"
"  font: 18pt \"Tlwg Mono\"; \n"
"  border-radius: 10px; \n"
"  border-color: black;\n"
"  border-width: 2px;\n"
"  border-style: inset;\n"
"  background-color: rgb(238, 238, 236);\n"
"}")
        self.toolButton_8.setObjectName("toolButton_8")
        self.gridLayout.addWidget(self.toolButton_8, 2, 0, 1, 1)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(20, 330, 741, 57))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_5.setStyleSheet("font: bold 11pt \"Tlwg Mono\";")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox.setStyleSheet("font: 12pt \"Tlwg Mono\";")
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_3.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox_2.setStyleSheet("font: 12pt \"Tlwg Mono\";")
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout_3.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox_3.setStyleSheet("font: 12pt \"Tlwg Mono\";")
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout_3.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox_4.setStyleSheet("font: 12pt \"Tlwg Mono\";")
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout_3.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox_5.setStyleSheet("font: 12pt \"Tlwg Mono\";")
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout_3.addWidget(self.checkBox_5)
        self.checkBox_6 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox_6.setStyleSheet("font: 12pt \"Tlwg Mono\";")
        self.checkBox_6.setObjectName("checkBox_6")
        self.horizontalLayout_3.addWidget(self.checkBox_6)
        self.checkBox_8 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox_8.setStyleSheet("font: 12pt \"Tlwg Mono\";")
        self.checkBox_8.setObjectName("checkBox_8")
        self.horizontalLayout_3.addWidget(self.checkBox_8)
        self.checkBox_7 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox_7.setStyleSheet("font: 12pt \"Tlwg Mono\";")
        self.checkBox_7.setObjectName("checkBox_7")
        self.horizontalLayout_3.addWidget(self.checkBox_7)
        self.checkBox_10 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox_10.setStyleSheet("font: 12pt \"Tlwg Mono\";")
        self.checkBox_10.setObjectName("checkBox_10")
        self.horizontalLayout_3.addWidget(self.checkBox_10)
        self.checkBox_11 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox_11.setStyleSheet("font: 12pt \"Tlwg Mono\";")
        self.checkBox_11.setObjectName("checkBox_11")
        self.horizontalLayout_3.addWidget(self.checkBox_11)
        self.checkBox_15 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox_15.setStyleSheet("font: 12pt \"Tlwg Mono\";")
        self.checkBox_15.setObjectName("checkBox_15")
        self.horizontalLayout_3.addWidget(self.checkBox_15)
        self.checkBox_12 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox_12.setStyleSheet("font: 12pt \"Tlwg Mono\";")
        self.checkBox_12.setObjectName("checkBox_12")
        self.horizontalLayout_3.addWidget(self.checkBox_12)
        self.checkBox_14 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox_14.setStyleSheet("font: 12pt \"Tlwg Mono\";")
        self.checkBox_14.setObjectName("checkBox_14")
        self.horizontalLayout_3.addWidget(self.checkBox_14)
        self.checkBox_9 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox_9.setStyleSheet("font: 12pt \"Tlwg Mono\";")
        self.checkBox_9.setObjectName("checkBox_9")
        self.horizontalLayout_3.addWidget(self.checkBox_9)
        self.checkBox_16 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox_16.setStyleSheet("font: 12pt \"Tlwg Mono\";")
        self.checkBox_16.setObjectName("checkBox_16")
        self.horizontalLayout_3.addWidget(self.checkBox_16)
        self.checkBox_13 = QtWidgets.QCheckBox(self.layoutWidget3)
        self.checkBox_13.setStyleSheet("font: 12pt \"Tlwg Mono\";")
        self.checkBox_13.setObjectName("checkBox_13")
        self.horizontalLayout_3.addWidget(self.checkBox_13)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(21, 31, 16, 17))
        self.label_2.setStyleSheet("font: 11pt bold \"Tlwg Mono\";")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.layoutWidget4 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(20, 20, 341, 35))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget4)
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    font: bold 11pt \"Tlwg Mono\";\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk {\n"
"    font: bold 11pt \"Tlwg Mono\";\n"
"    background-color: rgb(196, 233, 190);\n"
"    width: 10px;\n"
"    margin: 0.5px;\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout.addWidget(self.progressBar)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_6.setStyleSheet("font: bold 11pt \"Tlwg Mono\";")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.layoutWidget5 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget5.setGeometry(QtCore.QRect(290, 60, 71, 81))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget5)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_12.setStyleSheet("font: bold 11pt \"Tlwg Mono\";")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12, 0, QtCore.Qt.AlignHCenter)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_11.setStyleSheet("font: bold 11pt \"Tlwg Mono\";")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_4.addWidget(self.label_11, 0, QtCore.Qt.AlignHCenter)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_9.setStyleSheet("font: bold 11pt \"Tlwg Mono\";")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9, 0, QtCore.Qt.AlignHCenter)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 200, 351, 41))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setStyleSheet("font: 12pt bold \"Tlwg Mono\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4, 0, QtCore.Qt.AlignHCenter)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setStyleSheet("font: 12pt bold \"Tlwg Mono\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(260, 150, 41, 41))
        self.label_7.setStyleSheet("QLabel {background-color : yellow; border-color : black; border-width : 1px; border-style : solid; border-radius : 10px; min-height: 20px; min-width: 20px}")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(80, 150, 41, 41))
        self.label_8.setStyleSheet("QLabel {background-color : yellow; border-color : black; border-width : 1px; border-style : solid; border-radius : 10px; min-height: 20px; min-width: 20px}")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 768, 22))
        self.menubar.setObjectName("menubar")
        self.menuSISTEMA_DE_ALARMA = QtWidgets.QMenu(self.menubar)
        self.menuSISTEMA_DE_ALARMA.setObjectName("menuSISTEMA_DE_ALARMA")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar.addAction(self.menuSISTEMA_DE_ALARMA.menuAction())

        self.retranslateUi(MainWindow)
        self.horizontalSlider.sliderMoved['int'].connect(self.progressBar.setValue)
        self.checkBox_2.stateChanged['int'].connect(self.label_7.hide)
        self.checkBox_2.stateChanged['int'].connect(self.label_7.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "ESC"))
        self.pushButton_2.setText(_translate("MainWindow", "ENTER"))
        self.pushButton_3.setText(_translate("MainWindow", "PANICO"))
        self.pushButton_4.setText(_translate("MainWindow", "BOMBEROS"))
        self.label.setText(_translate("MainWindow", "SIMULACION ESTADO DE LA BATERIA "))
        self.toolButton_2.setText(_translate("MainWindow", "1"))
        self.toolButton_5.setText(_translate("MainWindow", "4"))
        self.toolButton_9.setText(_translate("MainWindow", "9"))
        self.toolButton_13.setText(_translate("MainWindow", "0"))
        self.toolButton_3.setText(_translate("MainWindow", "2"))
        self.toolButton_4.setText(_translate("MainWindow", "3"))
        self.toolButton_10.setText(_translate("MainWindow", "8"))
        self.toolButton_7.setText(_translate("MainWindow", "5"))
        self.toolButton_12.setText(_translate("MainWindow", "#"))
        self.toolButton_11.setText(_translate("MainWindow", "*"))
        self.toolButton_6.setText(_translate("MainWindow", "6"))
        self.toolButton_8.setText(_translate("MainWindow", "7"))
        self.label_5.setText(_translate("MainWindow", "SIMULACION ESTADO DE LOS SENSORES"))
        self.checkBox.setText(_translate("MainWindow", "1"))
        self.checkBox_2.setText(_translate("MainWindow", "2"))
        self.checkBox_3.setText(_translate("MainWindow", "3"))
        self.checkBox_4.setText(_translate("MainWindow", "4"))
        self.checkBox_5.setText(_translate("MainWindow", "5"))
        self.checkBox_6.setText(_translate("MainWindow", "6"))
        self.checkBox_8.setText(_translate("MainWindow", "7"))
        self.checkBox_7.setText(_translate("MainWindow", "8"))
        self.checkBox_10.setText(_translate("MainWindow", "9"))
        self.checkBox_11.setText(_translate("MainWindow", "10"))
        self.checkBox_15.setText(_translate("MainWindow", "11"))
        self.checkBox_12.setText(_translate("MainWindow", "12"))
        self.checkBox_14.setText(_translate("MainWindow", "13"))
        self.checkBox_9.setText(_translate("MainWindow", "14"))
        self.checkBox_16.setText(_translate("MainWindow", "15"))
        self.checkBox_13.setText(_translate("MainWindow", "16"))
        self.label_6.setText(_translate("MainWindow", "BATERIA"))
        self.label_12.setText(_translate("MainWindow", "MODO 0"))
        self.label_11.setText(_translate("MainWindow", "MODO 1"))
        self.label_9.setText(_translate("MainWindow", "ERROR"))
        self.label_4.setText(_translate("MainWindow", "ARMADA"))
        self.label_3.setText(_translate("MainWindow", "BATERIA"))
        self.menuSISTEMA_DE_ALARMA.setTitle(_translate("MainWindow", "SISTEMA DE SEGURIDAD PARA HOGARES SSH-101"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
